import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

// Font InterDisplay local
const interDisplay = localFont({
  src: [
    {
      path: "./fonts/InterDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/InterDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/InterDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-interdisplay",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* gắn biến font vào body, giữ class antialiased */}
      <body className={`${interDisplay.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
